### ISSUE TITLE
RFE: Playbook assumes root

### ISSUE THREAD

**Issue by christianh814** [christianh814/ocp4-upi-helpernode#18]
You should be able to run the playbook as a non root user by simply adding `become: yes` and make `-K` a requirement.

**Comment by vchintal** [comment]
Since the entire playbook is mostly touching resources protected under root, we just need to add `-b -K` to the ansible-playbook command when running as root, so that there are no changes to code; only one additional line to be added to README. 

Or create `ansible.cfg` in the root folder with the contents:
```
[privilege_escalation]
become=true
become_ask_pass=true
```

Happy to volunteer if need be 😉!
